### ISSUE TITLE
injection detection "slice out of bounds" panic

### ISSUE THREAD

**Issue by david415** [david415/HoneyBadger#2]
I thought I had fixed getOverlapBytes... and indeed all the unit tests now pass so this is confusing.

I need to fix this "slice bounds out of range" panic... and it looks like the problem might be in getRingSlice... perhaps i need to make the unit tests for getRingSlice more complete... or might there be a more subtle bug? We shall soon find out. Looky here:

./honeyBadger -i=lo -f="tcp port 9666"
2015/01/21 20:48:53 TCP_CONNECTION_REQUEST
2015/01/21 20:48:53 TCP_CONNECTION_ESTABLISHED
2015/01/21 20:48:53 TCP_DATA_TRANSFER
2015/01/21 20:48:55 expected tcp Sequence from server; payload len 5
2015/01/21 20:48:56 expected tcp Sequence from server; payload len 4
2015/01/21 20:48:57 expected tcp Sequence from server; payload len 5
2015/01/21 20:48:58 expected tcp Sequence from server; payload len 4
2015/01/21 20:48:59 expected tcp Sequence from server; payload len 4
2015/01/21 20:49:01 expected tcp Sequence from server; payload len 4
2015/01/21 20:49:02 expected tcp Sequence from server; payload len 4
2015/01/21 20:49:03 expected tcp Sequence from server; payload len 4
2015/01/21 20:49:04 expected tcp Sequence from server; payload len 4
2015/01/21 20:49:04 overlap case: TCP.Seq 293468048 before nextSeqPtr 293468052
panic: runtime error: slice bounds out of range

goroutine 21 [running]:
runtime.panic(0x5a0380, 0x9592cf)
        /home/human/golang-empire/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/david415/HoneyBadger.getRingSlice(0xc209072fa0, 0xc209072fc0, 0x117df790, 0x4, 0x0, 0x0, 0x0)
        /home/human/golang-empire/gopkg/src/github.com/david415/HoneyBadger/tcpFlowTracking.go:277 +0x720
github.com/david415/HoneyBadger.(*Connection).getOverlapBytes(0xc20802c4e0, 0xc209072fa0, 0xc209072fc0, 0x117df790, 0x117df79c, 0x0, 0x0, 0x0, 0xdc32064000000002, 0xc20801a47a)
        /home/human/golang-empire/gopkg/src/github.com/david415/HoneyBadger/tcpFlowTracking.go:322 +0x375
github.com/david415/HoneyBadger.(*Connection).isInjection(0xc20802c4e0, 0xc20801a46e, 0x14, 0x34, 0xc20801a482, 0x20, 0x20, 0x608f003400000504, 0xdc32064000000002, 0xc20801a47a, ...)
        /home/human/golang-empire/gopkg/src/github.com/david415/HoneyBadger/tcpFlowTracking.go:339 +0xda
github.com/david415/HoneyBadger.(*Connection).stateDataTransfer(0xc20802c4e0, 0xc20801a46e, 0x14, 0x34, 0xc20801a482, 0x20, 0x20, 0x608f003400000504, 0xdc32064000000002, 0xc20801a47a, ...)
        /home/human/golang-empire/gopkg/src/github.com/david415/HoneyBadger/tcpFlowTracking.go:441 +0x3e6
github.com/david415/HoneyBadger.(*Connection).receivePacket(0xc20802c4e0, 0xc20801a46e, 0x14, 0x34, 0xc20801a482, 0x20, 0x20, 0x608f003400000504, 0xdc32064000000002, 0xc20801a47a, ...)
        /home/human/golang-empire/gopkg/src/github.com/david415/HoneyBadger/tcpFlowTracking.go:629 +0x167
github.com/david415/HoneyBadger.decodeTcp(0xc208004240, 0xc2090703e0, 0xc2080042a0)
        /home/human/golang-empire/gopkg/src/github.com/david415/HoneyBadger/tcpFlowTracking.go:760 +0x6c4
created by github.com/david415/HoneyBadger.StartDecodingTcp
        /home/human/golang-empire/gopkg/src/github.com/david415/HoneyBadger/tcpFlowTracking.go:723 +0x59

**Comment by david415** [comment]
wow that was a stupid bug... and was easy to fix when I gave it a few minutes more of my attention =-)
I was passing the TCP Sequence number instead of a byte slice offset. ha!
