### ISSUE TITLE
fix bug in detectInjection

### ISSUE THREAD

**Issue by david415** [david415/HoneyBadger#30]
panic: getRingSlice: sliceStart 7240 >= head len 1900

goroutine 1388 [running]:
github.com/david415/HoneyBadger.getRingSlice(0xc2095b5a40, 0xc2095b5ac0, 0x1c48, 0x0, 0x0, 0x0, 0x0)
        /home/human/golang/gopkg/src/github.com/david415/HoneyBadger/retrospective.go:132 +0x293
github.com/david415/HoneyBadger.(*Connection).getOverlapBytes(0xc2095a5b80, 0xc2095b5a40, 0xc2095b5ac0, 0x3063618f, 0x30636cde, 0x0, 0x0, 0x0, 0x0, 0x5d1db96a)
        /home/human/golang/gopkg/src/github.com/david415/HoneyBadger/state_machine.go:262 +0x3f0
github.com/david415/HoneyBadger.(*Connection).detectInjection(0xc2095a5b80, 0xecc7cbed8, 0xc205c86860, 0x9d3a40, 0x1, 0x4, 0x4, 0x2a61eb9, 0x0, 0x5d1db96a, ...)

**Comment by david415** [comment]
i think this one is fixed
