### ISSUE TITLE
Connection Close race

### ISSUE THREAD

**Issue by david415** [david415/HoneyBadger#42]
I'm not sure how to efficiently prevent this race. Currently there is some pretty hacky code in Connection's Close (in state_machine.go). Does Mischief have good design suggestions for avoid the race and handling the Close?

The counterpart to this located packetSource/service.go where we create the Connection.

panic: send on closed channel

goroutine 9 [running]:
github.com/david415/HoneyBadger/packetSource.(*Inquisitor).dispatchPackets(0xc2090de000)
        /home/human/golang/gopkg/src/github.com/david415/HoneyBadger/packetSource/service.go:253 +0x411
created by github.com/david415/HoneyBadger/packetSource.(*Inquisitor).Start
        /home/human/golang/gopkg/src/github.com/david415/HoneyBadger/packetSource/service.go:100 +0x82

goroutine 1 [chan receive, 2 minutes]:
main.main()
        /home/human/golang/gopkg/src/github.com/david415/HoneyBadger/cmd/honeyBadger/main.go:103 +0xb8a

goroutine 5 [syscall, 2 minutes]:
os/signal.loop()
        /home/human/golang/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /home/human/golang/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [select, 2 minutes]:
github.com/david415/HoneyBadger/logging.(*AttackJsonLogger).receiveReports(0xc2090da450)
        /home/human/golang/gopkg/src/github.com/david415/HoneyBadger/logging/attack_logger.go:74 +0x105
created by github.com/david415/HoneyBadger/logging.(*AttackJsonLogger).Start
        /home/human/golang/gopkg/src/github.com/david415/HoneyBadger/logging/attack_logger.go:65 +0x32

**Comment by david415** [comment]
hey here's an ugly hacky way to mitigate the close race
https://github.com/david415/HoneyBadger/tree/david-fix-close

**Comment by david415** [comment]
To be clear... this bug was fixed... but I'd rather improve the code quality before closing this ticket. Mischief's expert code review skills are desired to help resolve this code quality issue.

**Comment by david415** [comment]
Here's my latest attempt to fix this race:
https://github.com/david415/HoneyBadger/tree/42-fix-close-race-1

however improved this looks... it only nominally works; deadlocks upon control-c instead of graceful shutdown.

Mischeif, what do you think?

**Comment by david415** [comment]
the closeAllConnections doesn't work in that branch so i experimented with using a waitgroup to help with that here in this branch:
https://github.com/david415/HoneyBadger/tree/42-fix-close-race-1-waitgroup-1

unfortunately i wasn't able to get my connectionpool unit tests to pass. i might try synchronizing with channels or more drastically rewriting the connectionpool close all connections tests.

**Comment by david415** [comment]
and see here for my attempt to use channels to synchronize the CloseAllConnections
https://github.com/david415/HoneyBadger/tree/42-fix-close-race-1-doneChan-1

unit test fails in the same way:
2015/04/25 00:57:28 Stop() - connection stopped: 1.2.3.4:1-2.3.4.5:2
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
testing.RunTests(0x8bc418, 0x9f5e80, 0x12, 0x12, 0x1)
	/home/user/go/src/testing/testing.go:556 +0xdc3
testing.(*M).Run(0xc2080300f0, 0xf28e80)
	/home/user/go/src/testing/testing.go:485 +0xe1
main.main()
	github.com/david415/HoneyBadger/_test/_testmain.go:86 +0x28d

goroutine 5 [chan receive]:
github.com/david415/HoneyBadger.(*ConnectionPool).CloseAllConnections(0xc20987f100, 0x0)
	/home/user/go/gopath/src/github.com/david415/HoneyBadger/connection_pool.go:103 +0x1b5

**Comment by david415** [comment]
fixed!
